### ISSUE TITLE
Please add a LICENSE to project

### ISSUE THREAD

**Issue by nmoadev** [jishi/node-sqs-poller#4]
Hi!

This library looks solid and I'm considering using it. However, without any software license, I won't be able to use it.

Could you please add a license file to your project?

Thanks!

**Comment by jishi** [comment]
No problem, I thought specifying it in package.json would be enough, but seems reasonable to also include a LICENSE file.

**Comment by jishi** [comment]
Just published 1.0.4 which include the ISC license.
